version: '3'

services:
  app1:
    build: ./app1
    container_name: app1

  app2:
    build: ./app2
    container_name: app2

  app3:
    build: ./app1
    container_name: app3

  nginx:
    image: nginx:latest
    container_name: nginx_lb
    ports:
      - "8080:80"
    volumes:                           # ✅ Inside nginx service
      - ./nginx:/etc/nginx:ro
    depends_on:                        # ✅ Also inside nginx service
      - app1
      - app2
      - app3

    restart: always
