version: '3'

services:
  app1:
    build: ./app1
    container_name: app1
  app2:
    build: ./app2
    container_name: app2
  nginx:
    image: nginx:latest
    container_name: nginx_lb
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
